"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins

if TYPE_CHECKING:
    from .collectionerror import CollectionError, CollectionErrorData
    from .gleanbaseerror import GleanBaseError
    from .gleandataerror import GleanDataError, GleanDataErrorData
    from .gleanerror import GleanError
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "CollectionError",
    "CollectionErrorData",
    "GleanBaseError",
    "GleanDataError",
    "GleanDataErrorData",
    "GleanError",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "CollectionError": ".collectionerror",
    "CollectionErrorData": ".collectionerror",
    "GleanBaseError": ".gleanbaseerror",
    "GleanDataError": ".gleandataerror",
    "GleanDataErrorData": ".gleandataerror",
    "GleanError": ".gleanerror",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
