"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from langcache.types import BaseModel
from typing import Dict
from typing_extensions import TypedDict


class CacheEntryTypedDict(TypedDict):
    r"""A cache entry"""

    id: str
    r"""Unique identifier for the cache entry."""
    prompt: str
    r"""The prompt associated with the cache entry."""
    response: str
    r"""The response associated with the cache entry."""
    attributes: Dict[str, str]
    r"""The key-value pairs of attributes that are associated with the cache entry."""
    similarity: float
    r"""The similarity metric used for similarity comparison."""


class CacheEntry(BaseModel):
    r"""A cache entry"""

    id: str
    r"""Unique identifier for the cache entry."""

    prompt: str
    r"""The prompt associated with the cache entry."""

    response: str
    r"""The response associated with the cache entry."""

    attributes: Dict[str, str]
    r"""The key-value pairs of attributes that are associated with the cache entry."""

    similarity: float
    r"""The similarity metric used for similarity comparison."""
