# coding: utf-8

"""
    aind-slims-service

     ## aind-slims-service  Service to pull data from SLIMS.  

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slims_service_async_client.models.histology_reagent_data import HistologyReagentData

class TestHistologyReagentData(unittest.TestCase):
    """HistologyReagentData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistologyReagentData:
        """Test HistologyReagentData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistologyReagentData`
        """
        model = HistologyReagentData()
        if include_optional:
            return HistologyReagentData(
                name = '',
                source = '',
                lot_number = ''
            )
        else:
            return HistologyReagentData(
        )
        """

    def testHistologyReagentData(self):
        """Test HistologyReagentData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
