# Generated by ariadne-codegen
# Source: graphql/

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import KnowledgeSourceType
from .fragments import (
    DateTimeParts,
    MachineUserActorParts,
    MutationErrorParts,
    SystemActorParts,
    UserActorParts,
)


class CreateKnowledgeSource(BaseModel):
    create_knowledge_source: "CreateKnowledgeSourceCreateKnowledgeSource" = Field(
        alias="createKnowledgeSource"
    )


class CreateKnowledgeSourceCreateKnowledgeSource(BaseModel):
    knowledge_source: Optional[
        Annotated[
            Union[
                "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemap",
                "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrl",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="knowledgeSource")
    error: Optional["CreateKnowledgeSourceCreateKnowledgeSourceError"]


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemap(
    BaseModel
):
    typename__: Literal["KnowledgeSourceSitemap"] = Field(alias="__typename")
    id: str
    url: str
    type: KnowledgeSourceType
    status: Union[
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusPending",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusIndexed",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusFailed",
    ] = Field(discriminator="typename__")
    created_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapCreatedAt" = Field(
        alias="createdAt"
    )
    created_by: Union[
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapCreatedByUserActor",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapCreatedBySystemActor",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapCreatedByMachineUserActor",
    ] = Field(alias="createdBy", discriminator="typename__")
    updated_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapUpdatedAt" = Field(
        alias="updatedAt"
    )
    updated_by: Union[
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapUpdatedByUserActor",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapUpdatedBySystemActor",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapUpdatedByMachineUserActor",
    ] = Field(alias="updatedBy", discriminator="typename__")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusPending(
    BaseModel
):
    typename__: Literal["IndexingStatusPending"] = Field(alias="__typename")
    started_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusPendingStartedAt" = Field(
        alias="startedAt"
    )


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusPendingStartedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusIndexed(
    BaseModel
):
    typename__: Literal["IndexingStatusIndexed"] = Field(alias="__typename")
    indexed_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusIndexedIndexedAt" = Field(
        alias="indexedAt"
    )


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusIndexedIndexedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusFailed(
    BaseModel
):
    typename__: Literal["IndexingStatusFailed"] = Field(alias="__typename")
    failed_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusFailedFailedAt" = Field(
        alias="failedAt"
    )
    reason: str


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusFailedFailedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapCreatedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapCreatedByUserActor(
    UserActorParts
):
    typename__: Literal["UserActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapCreatedBySystemActor(
    SystemActorParts
):
    typename__: Literal["SystemActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapCreatedByMachineUserActor(
    MachineUserActorParts
):
    typename__: Literal["MachineUserActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapUpdatedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapUpdatedByUserActor(
    UserActorParts
):
    typename__: Literal["UserActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapUpdatedBySystemActor(
    SystemActorParts
):
    typename__: Literal["SystemActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapUpdatedByMachineUserActor(
    MachineUserActorParts
):
    typename__: Literal["MachineUserActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrl(
    BaseModel
):
    typename__: Literal["KnowledgeSourceUrl"] = Field(alias="__typename")
    id: str
    url: str
    type: KnowledgeSourceType
    status: Union[
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusPending",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusIndexed",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusFailed",
    ] = Field(discriminator="typename__")
    created_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlCreatedAt" = Field(
        alias="createdAt"
    )
    created_by: Union[
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlCreatedByUserActor",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlCreatedBySystemActor",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlCreatedByMachineUserActor",
    ] = Field(alias="createdBy", discriminator="typename__")
    updated_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlUpdatedAt" = Field(
        alias="updatedAt"
    )
    updated_by: Union[
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlUpdatedByUserActor",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlUpdatedBySystemActor",
        "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlUpdatedByMachineUserActor",
    ] = Field(alias="updatedBy", discriminator="typename__")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusPending(
    BaseModel
):
    typename__: Literal["IndexingStatusPending"] = Field(alias="__typename")
    started_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusPendingStartedAt" = Field(
        alias="startedAt"
    )


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusPendingStartedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusIndexed(
    BaseModel
):
    typename__: Literal["IndexingStatusIndexed"] = Field(alias="__typename")
    indexed_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusIndexedIndexedAt" = Field(
        alias="indexedAt"
    )


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusIndexedIndexedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusFailed(
    BaseModel
):
    typename__: Literal["IndexingStatusFailed"] = Field(alias="__typename")
    failed_at: "CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusFailedFailedAt" = Field(
        alias="failedAt"
    )
    reason: str


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusFailedFailedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlCreatedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlCreatedByUserActor(
    UserActorParts
):
    typename__: Literal["UserActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlCreatedBySystemActor(
    SystemActorParts
):
    typename__: Literal["SystemActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlCreatedByMachineUserActor(
    MachineUserActorParts
):
    typename__: Literal["MachineUserActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlUpdatedAt(
    DateTimeParts
):
    pass


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlUpdatedByUserActor(
    UserActorParts
):
    typename__: Literal["UserActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlUpdatedBySystemActor(
    SystemActorParts
):
    typename__: Literal["SystemActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlUpdatedByMachineUserActor(
    MachineUserActorParts
):
    typename__: Literal["MachineUserActor"] = Field(alias="__typename")


class CreateKnowledgeSourceCreateKnowledgeSourceError(MutationErrorParts):
    pass


CreateKnowledgeSource.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSource.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemap.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusPending.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusIndexed.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceSitemapStatusIndexingStatusFailed.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrl.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusPending.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusIndexed.model_rebuild()
CreateKnowledgeSourceCreateKnowledgeSourceKnowledgeSourceKnowledgeSourceUrlStatusIndexingStatusFailed.model_rebuild()
