# Generated by ariadne-codegen
# Source: graphql/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import CustomerCardConfigParts, MutationErrorParts


class CreateCustomerCardConfig(BaseModel):
    create_customer_card_config: "CreateCustomerCardConfigCreateCustomerCardConfig" = (
        Field(alias="createCustomerCardConfig")
    )


class CreateCustomerCardConfigCreateCustomerCardConfig(BaseModel):
    customer_card_config: Optional[
        "CreateCustomerCardConfigCreateCustomerCardConfigCustomerCardConfig"
    ] = Field(alias="customerCardConfig")
    error: Optional["CreateCustomerCardConfigCreateCustomerCardConfigError"]


class CreateCustomerCardConfigCreateCustomerCardConfigCustomerCardConfig(
    CustomerCardConfigParts
):
    pass


class CreateCustomerCardConfigCreateCustomerCardConfigError(MutationErrorParts):
    pass


CreateCustomerCardConfig.model_rebuild()
CreateCustomerCardConfigCreateCustomerCardConfig.model_rebuild()
