# Generated by ariadne-codegen
# Source: graphql/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import WorkspaceParts


class MyWorkspace(BaseModel):
    my_workspace: Optional["MyWorkspaceMyWorkspace"] = Field(alias="myWorkspace")


class MyWorkspaceMyWorkspace(WorkspaceParts):
    pass


MyWorkspace.model_rebuild()
