# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: a42/label/object.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from . import data


@dataclass
class Position(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
    z: float = betterproto.float_field(3)


@dataclass
class Dimensions(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
    z: float = betterproto.float_field(3)


@dataclass
class ObjectBBox(betterproto.Message):
    timestamp_ns: int = betterproto.uint64_field(1)
    position: "Position" = betterproto.message_field(2)
    dimension: "Dimensions" = betterproto.message_field(3)
    pointcloud: data.PointCloud = betterproto.message_field(4)
