# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.media_update_response_meta_type import MediaUpdateResponseMetaType


class MediaUpdateResponseMetaParams(typing_extensions.TypedDict):
    request_id: typing_extensions.NotRequired[str]
    org_id: typing_extensions.NotRequired[str]
    project_id: typing_extensions.NotRequired[str]
    version: typing_extensions.NotRequired[str]
    type: typing_extensions.NotRequired[MediaUpdateResponseMetaType]
