"""This file was generated by xsdata, v25.4, on 2025-05-21 12:08:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

from colour_cxf.cxf3.delta_cielab import DeltaCielab
from colour_cxf.cxf3.delta_custom import DeltaCustom

__NAMESPACE__ = "http://colorexchangeformat.com/CxF3-core"


@dataclass
class ColorDifferenceValues:
    """
    CIELab Color difference values compared to the referenced standard.
    """

    class Meta:
        namespace = "http://colorexchangeformat.com/CxF3-core"

    delta_cielab_or_delta_custom: list[DeltaCielab | DeltaCustom] = field(
        default_factory=list,
        metadata={
            "type": "Elements",
            "choices": (
                {
                    "name": "DeltaCIELab",
                    "type": DeltaCielab,
                },
                {
                    "name": "DeltaCustom",
                    "type": DeltaCustom,
                },
            ),
        },
    )
