"""This file was generated by xsdata, v25.4, on 2025-05-21 12:08:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

__NAMESPACE__ = "http://colorexchangeformat.com/CxF3-core"


@dataclass
class ColorPantoneHexachrome:
    """
    ColorSpace type that holds Pantone Hexachrome values.

    Parameters
    ----------
    cyan
        Percent cyan 0 (inclusive) to 100 (inclusive).
    magenta
        Percent magenta 0 (inclusive) to 100 (inclusive).
    yellow
        Percent yellow 0 (inclusive) to 100 (inclusive).
    black
        Percent black 0 (inclusive) to 100 (inclusive).
    orange
        Percent orange 0 (inclusive) to 100 (inclusive).
    green
        Percent green 0 (inclusive) to 100 (inclusive).
    profile_specification
    name
    color_specification
    """

    class Meta:
        namespace = "http://colorexchangeformat.com/CxF3-core"

    cyan: None | float = field(
        default=None,
        metadata={
            "name": "Cyan",
            "type": "Element",
            "required": True,
            "min_inclusive": 0.0,
            "max_inclusive": 100.0,
        },
    )
    magenta: None | float = field(
        default=None,
        metadata={
            "name": "Magenta",
            "type": "Element",
            "required": True,
            "min_inclusive": 0.0,
            "max_inclusive": 100.0,
        },
    )
    yellow: None | float = field(
        default=None,
        metadata={
            "name": "Yellow",
            "type": "Element",
            "required": True,
            "min_inclusive": 0.0,
            "max_inclusive": 100.0,
        },
    )
    black: None | float = field(
        default=None,
        metadata={
            "name": "Black",
            "type": "Element",
            "required": True,
            "min_inclusive": 0.0,
            "max_inclusive": 100.0,
        },
    )
    orange: None | float = field(
        default=None,
        metadata={
            "name": "Orange",
            "type": "Element",
            "required": True,
            "min_inclusive": 0.0,
            "max_inclusive": 100.0,
        },
    )
    green: None | float = field(
        default=None,
        metadata={
            "name": "Green",
            "type": "Element",
            "required": True,
            "min_inclusive": 0.0,
            "max_inclusive": 100.0,
        },
    )
    profile_specification: None | str = field(
        default=None,
        metadata={
            "name": "ProfileSpecification",
            "type": "Attribute",
        },
    )
    name: None | str = field(
        default=None,
        metadata={
            "name": "Name",
            "type": "Attribute",
        },
    )
    color_specification: None | str = field(
        default=None,
        metadata={
            "name": "ColorSpecification",
            "type": "Attribute",
            "required": True,
        },
    )
