"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from lambdadb.errors import LambdaDBError
from lambdadb.types import BaseModel
from typing import Optional


class ResourceNotFoundErrorData(BaseModel):
    message: Optional[str] = None


class ResourceNotFoundError(LambdaDBError):
    data: ResourceNotFoundErrorData

    def __init__(
        self,
        data: ResourceNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
