# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iot_grpc/measurements.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'iot_grpc/measurements.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1biot_grpc/measurements.proto\x12\x0bmeasurement\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb4\x01\n\x13MeasurementsRequest\x12,\n\x06tenant\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0e\n\x06meters\x18\x02 \x03(\t\x12\x10\n\x08order_by\x18\x03 \x01(\t\x12\x30\n\x0cmeasured_day\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04skip\x18\x05 \x01(\x05\x12\r\n\x05limit\x18\x06 \x01(\x05\"\xde\x01\n\x0bMeasurement\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x10\n\x08meter_id\x18\x02 \x01(\t\x12.\n\ncreated_ts\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_ts\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bmeasured_ts\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05value\x18\x06 \x01(\x01\x12\r\n\x05media\x18\x07 \x01(\t\"j\n\x14MeasurementsResponse\x12.\n\x0cmeasurements\x18\x01 \x03(\x0b\x32\x18.measurement.Measurement\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\x32n\n\x12MeasurementService\x12X\n\x0fGetMeasurements\x12 .measurement.MeasurementsRequest\x1a!.measurement.MeasurementsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_grpc.measurements_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEASUREMENTSREQUEST']._serialized_start=110
  _globals['_MEASUREMENTSREQUEST']._serialized_end=290
  _globals['_MEASUREMENT']._serialized_start=293
  _globals['_MEASUREMENT']._serialized_end=515
  _globals['_MEASUREMENTSRESPONSE']._serialized_start=517
  _globals['_MEASUREMENTSRESPONSE']._serialized_end=623
  _globals['_MEASUREMENTSERVICE']._serialized_start=625
  _globals['_MEASUREMENTSERVICE']._serialized_end=735
# @@protoc_insertion_point(module_scope)
