# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61970/base/wires/PhaseImpedanceData.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61970.base.wires import SinglePhaseKind_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_wires_dot_SinglePhaseKind__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@zepben/protobuf/cim/iec61970/base/wires/PhaseImpedanceData.proto\x12\'zepben.protobuf.cim.iec61970.base.wires\x1a=zepben/protobuf/cim/iec61970/base/wires/SinglePhaseKind.proto\"\xd8\x01\n\x12PhaseImpedanceData\x12\t\n\x01\x62\x18\x01 \x01(\x01\x12K\n\tfromPhase\x18\x02 \x01(\x0e\x32\x38.zepben.protobuf.cim.iec61970.base.wires.SinglePhaseKind\x12I\n\x07toPhase\x18\x03 \x01(\x0e\x32\x38.zepben.protobuf.cim.iec61970.base.wires.SinglePhaseKind\x12\t\n\x01g\x18\x04 \x01(\x01\x12\t\n\x01r\x18\x05 \x01(\x01\x12\t\n\x01x\x18\x06 \x01(\x01\x42/\n+com.zepben.protobuf.cim.iec61970.base.wiresP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.cim.iec61970.base.wires.PhaseImpedanceData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.zepben.protobuf.cim.iec61970.base.wiresP\001'
  _globals['_PHASEIMPEDANCEDATA']._serialized_start=173
  _globals['_PHASEIMPEDANCEDATA']._serialized_end=389
# @@protoc_insertion_point(module_scope)
