# Generated by ariadne-codegen
# Source: graphql/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import MutationErrorParts


class AddCustomerToTenants(BaseModel):
    add_customer_to_tenants: "AddCustomerToTenantsAddCustomerToTenants" = Field(
        alias="addCustomerToTenants"
    )


class AddCustomerToTenantsAddCustomerToTenants(BaseModel):
    error: Optional["AddCustomerToTenantsAddCustomerToTenantsError"]


class AddCustomerToTenantsAddCustomerToTenantsError(MutationErrorParts):
    pass


AddCustomerToTenants.model_rebuild()
AddCustomerToTenantsAddCustomerToTenants.model_rebuild()
