# Generated by ariadne-codegen
# Source: graphql/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import MutationErrorParts


class RemoveCustomerFromCustomerGroups(BaseModel):
    remove_customer_from_customer_groups: "RemoveCustomerFromCustomerGroupsRemoveCustomerFromCustomerGroups" = Field(
        alias="removeCustomerFromCustomerGroups"
    )


class RemoveCustomerFromCustomerGroupsRemoveCustomerFromCustomerGroups(BaseModel):
    error: Optional[
        "RemoveCustomerFromCustomerGroupsRemoveCustomerFromCustomerGroupsError"
    ]


class RemoveCustomerFromCustomerGroupsRemoveCustomerFromCustomerGroupsError(
    MutationErrorParts
):
    pass


RemoveCustomerFromCustomerGroups.model_rebuild()
RemoveCustomerFromCustomerGroupsRemoveCustomerFromCustomerGroups.model_rebuild()
