# Generated by ariadne-codegen
# Source: graphql/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import MutationErrorParts, ThreadParts


class UnassignThread(BaseModel):
    unassign_thread: "UnassignThreadUnassignThread" = Field(alias="unassignThread")


class UnassignThreadUnassignThread(BaseModel):
    thread: Optional["UnassignThreadUnassignThreadThread"]
    error: Optional["UnassignThreadUnassignThreadError"]


class UnassignThreadUnassignThreadThread(ThreadParts):
    pass


class UnassignThreadUnassignThreadError(MutationErrorParts):
    pass


UnassignThread.model_rebuild()
UnassignThreadUnassignThread.model_rebuild()
