
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-15T12:48:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d688e7843a95f91476d9b786bf4d9e80d50f389",
 "version": "0.41.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
