from sdvrp_py.rstypes import (
    InterOperator,
    IntraOperator,
    AcceptanceRuleType,
    RuinMethodType,
    Sorter,
    InputFormat,
)

def solve_sdvrp(
    random_seed: int,
    time_limit: float,
    blink_rate: float,
    inter_operators: list[InterOperator],
    intra_operators: list[IntraOperator],
    acceptance_rule_type: AcceptanceRuleType,
    lahc_length: int,
    sa_initial_temperature: float,
    sa_decay: float,
    ruin_method_type: RuinMethodType,
    sisrs_average_customers: int,
    sisrs_max_length: int,
    sisrs_split_rate: float,
    sisrs_preserved_probability: float,
    random_ruin_sizes: list[int],
    sorters: list[Sorter],
    sorter_values: list[float],
    capacity: int,
    demands: list[int],
    input_format: InputFormat,
    distance_matrix: list[int],
    coord_list_x: list[int],
    coord_list_y: list[int],
) -> list[list[tuple[int, int]]]: ...
