# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encoder/encoder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "encoder/encoder.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x65ncoder/encoder.proto\x12\x07\x65ncoder"e\n\x0e\x42lobCommitment\x12\x12\n\ncommitment\x18\x01 \x01(\x0c\x12\x19\n\x11length_commitment\x18\x02 \x01(\x0c\x12\x14\n\x0clength_proof\x18\x03 \x01(\x0c\x12\x0e\n\x06length\x18\x04 \x01(\r":\n\x0e\x45ncodingParams\x12\x14\n\x0c\x63hunk_length\x18\x01 \x01(\r\x12\x12\n\nnum_chunks\x18\x02 \x01(\r"S\n\x11\x45ncodeBlobRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x30\n\x0f\x65ncoding_params\x18\x02 \x01(\x0b\x32\x17.encoder.EncodingParams"\x8b\x01\n\x0f\x45ncodeBlobReply\x12+\n\ncommitment\x18\x01 \x01(\x0b\x32\x17.encoder.BlobCommitment\x12\x0e\n\x06\x63hunks\x18\x02 \x03(\x0c\x12;\n\x15\x63hunk_encoding_format\x18\x03 \x01(\x0e\x32\x1c.encoder.ChunkEncodingFormat*6\n\x13\x43hunkEncodingFormat\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05GNARK\x10\x01\x12\x07\n\x03GOB\x10\x02\x32O\n\x07\x45ncoder\x12\x44\n\nEncodeBlob\x12\x1a.encoder.EncodeBlobRequest\x1a\x18.encoder.EncodeBlobReply"\x00\x42/Z-github.com/Layr-Labs/eigenda/api/grpc/encoderb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "encoder.encoder_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z-github.com/Layr-Labs/eigenda/api/grpc/encoder"
    _globals["_CHUNKENCODINGFORMAT"]._serialized_start = 424
    _globals["_CHUNKENCODINGFORMAT"]._serialized_end = 478
    _globals["_BLOBCOMMITMENT"]._serialized_start = 34
    _globals["_BLOBCOMMITMENT"]._serialized_end = 135
    _globals["_ENCODINGPARAMS"]._serialized_start = 137
    _globals["_ENCODINGPARAMS"]._serialized_end = 195
    _globals["_ENCODEBLOBREQUEST"]._serialized_start = 197
    _globals["_ENCODEBLOBREQUEST"]._serialized_end = 280
    _globals["_ENCODEBLOBREPLY"]._serialized_start = 283
    _globals["_ENCODEBLOBREPLY"]._serialized_end = 422
    _globals["_ENCODER"]._serialized_start = 480
    _globals["_ENCODER"]._serialized_end = 559
# @@protoc_insertion_point(module_scope)
