# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .automation_response_data_workflow_item_conditions_conditions_item import (
    AutomationResponseDataWorkflowItemConditionsConditionsItemParams,
)
from .automation_response_data_workflow_item_conditions_next_item import (
    AutomationResponseDataWorkflowItemConditionsNextItemParams,
)


class AutomationResponseDataWorkflowItemConditionsParams(typing_extensions.TypedDict):
    kind: typing.Literal["conditions"]
    conditions: typing.Sequence[AutomationResponseDataWorkflowItemConditionsConditionsItemParams]
    next: typing_extensions.NotRequired[typing.Sequence[AutomationResponseDataWorkflowItemConditionsNextItemParams]]
