# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.media_list_response_meta_type import MediaListResponseMetaType


class MediaListResponseMetaParams(typing_extensions.TypedDict):
    request_id: typing_extensions.NotRequired[str]
    org_id: typing_extensions.NotRequired[str]
    project_id: typing_extensions.NotRequired[str]
    version: typing_extensions.NotRequired[str]
    type: typing_extensions.NotRequired[MediaListResponseMetaType]
    limit: typing_extensions.NotRequired[int]
    total: typing_extensions.NotRequired[int]
    page: typing_extensions.NotRequired[int]
    pages: typing_extensions.NotRequired[int]
