
dict_brams = {   
                    "model"     : {
                                    "name" : "BRAMS",
                                    "parameter" : "ams_08km",
                                    "long_name" : "Brazilian developments on the Regional Atmospheric Modeling System"
                                },
                    "variables" :  {  
                                    "t" : "TMP",
                                    "u" : "UGRD",
                                    "v" : "VGRD",
                                    "rh" : "RH",
                                    "g" : "HGT",
                                    "omega" : "VVEL",
                                    "u10m" : "UGRD",
                                    "v10m" : "VGRD",
                                    "t2m" : "TMP",
                                    "slp" : "PRMSL",
                                    "psfc" : "PRMSLMetar",
                                    "terrain" : "HGT",
                                    "sbcape" : "CAPE",
                                    "sbcin" : "CIN",
                                    "pw" : "PWAT",
                                    "precip" : "APCP",
                                    "acpcp":"ACPCP",
                                    "tveg1":"TVEG1",
                                    "tveg2":"TVEG2",
                                    "tveg3":"TVEG3",
                                    "tveg4":"TVEG4",
                                    "lhtfl": "LHTFL", 
                                    "shtfl":"SHTFL",
                                    "nswrs":"NSWRS",
                                    "nlwrs":"NLWRS",
                                    "albdo":"ALBDO",
                                    "ulwrf": "ULWRF", 
                                    "wtmpil": "WTMPIL", 
                                    "dpt":"DPT",
                                    "soilm1":"SOILM1",
                                    "soilm2": "SOILM2", 
                                    "soilm3":"SOILM3",
                                    "soilm4":"SOILM4",
                                    "hpbl": "HPBL", 
                                    "clmr":"CLMR",
                                    "vapmrt":"VAPMRT",
                                    "epot":"EPOT",
                                    "pres":"PRES",
                                    "ndvi1":"NDVI1",
                                    "ndvi2":"NDVI2",
                                    "ndvi3":"NDVI3",
                                    "ndvi4":"NDVI4",
                                    "lai1":"LAI1",
                                    "lai2":"LAI2",
                                    "lai3":"LAI3",
                                    "lai4":"LAI4",
                                    "hcdc":"HCDC",
                                    "mcdc":"MCDC"
                                },
                    "levels" :   {  
                                    "t" : "LVL",
                                    "u" : "LVL",
                                    "v" : "LVL",
                                    "rh" : "LVL",
                                    "g" : "LVL",
                                    "omega" : "LVL",
                                    "u10m" : "SFC",
                                    "v10m" : "SFC",
                                    "t2m" : "SFC",
                                    "slp" : "SFC",
                                    "psfc" : "SFC",
                                    "terrain" : "SFC",
                                    "sbcape" : "SFC",
                                    "sbcin" : "SFC",
                                    "pw" : "SFC",
                                    "precip" : "SFC",
                                    "acpcp":"SFC",
                                    "tveg1":"SFC",
                                    "tveg2":"SFC",
                                    "tveg3":"SFC",
                                    "tveg4":"SFC",
                                    "lhtfl": "SFC", 
                                    "shtfl":"SFC",
                                    "nswrs":"SFC",
                                    "nlwrs":"SFC",
                                    "albdo":"SFC",
                                    "ulwrf": "SFC", 
                                    "wtmpil": "SFC", 
                                    "dpt":"SFC",
                                    "soilm1":"SFC",
                                    "soilm2": "SFC", 
                                    "soilm3":"SFC",
                                    "soilm4":"SFC",
                                    "hpbl": "SFC", 
                                    "clmr":"LVL",
                                    "vapmrt":"LVL",
                                    "epot":"LVL",
                                    "pres":"SFC",
                                    "ndvi1":"SFC",
                                    "ndvi2":"SFC",
                                    "ndvi3":"SFC",
                                    "ndvi4":"SFC",
                                    "lai1":"SFC",
                                    "lai2":"SFC",
                                    "lai3":"SFC",
                                    "lai4":"SFC",
                                    "hcdc":"SFC",
                                    "mcdc":"SFC"                                 
                                },
                    "types" :   {  
                                    "t" : "ALL",
                                    "u" : "ALL",
                                    "v" : "ALL",
                                    "rh" : "ALL",
                                    "g" : "ALL",
                                    "omega" : "ALL",
                                    "u10m" : "ALL",
                                    "v10m" : "ALL",
                                    "t2m" : "ALL",
                                    "slp" : "ALL",
                                    "psfc" : "ALL",
                                    "terrain" : "ALL",
                                    "sbcape" : "ALL",
                                    "sbcin" : "ALL",
                                    "pw" : "ALL",
                                    "precip" : "FCT",
                                    "cssf" : "FCT",
                                    "clsf" : "FCT",
                                    "role" : "FCT",
                                    "acpcp":"ALL",
                                    "tveg1":"ALL",
                                    "tveg2":"ALL",
                                    "tveg3":"ALL",
                                    "tveg4":"ALL",
                                    "lhtfl": "ALL", 
                                    "shtfl":"ALL",
                                    "nswrs":"ALL",
                                    "nlwrs":"ALL",
                                    "albdo":"ALL",
                                    "ulwrf": "ALL", 
                                    "wtmpil": "ALL", 
                                    "dpt":"ALL",
                                    "soilm1":"ALL",
                                    "soilm2": "ALL", 
                                    "soilm3":"ALL",
                                    "soilm4":"ALL",
                                    "hpbl": "ALL", 
                                    "clmr":"ALL",
                                    "vapmrt":"ALL",
                                    "epot":"ALL",
                                    "pres":"ALL",
                                    "ndvi1":"ALL",
                                    "ndvi2":"ALL",
                                    "ndvi3":"ALL",
                                    "ndvi4":"ALL",
                                    "lai1":"ALL",
                                    "lai2":"ALL",
                                    "lai3":"ALL",
                                    "lai4":"ALL",
                                    "hcdc":"ALL",
                                    "mcdc":"ALL"
                                }, 
                   "desc" :  { 
                                    "t" : { "name" : "Temperature", "unit": "C"},
                                    "u" : { "name" : "U-Component of Wind", "unit": "m/s"},
                                    "v" : { "name" : "V-Component of Wind", "unit": "m/s"},
                                    "rh" : { "name" : "Relative Humidity", "unit": "%"},
                                    "g" : { "name" : "Geopotential Height", "unit": "gpm"},
                                    "omega" : { "name" : "omega", "unit": ""},
                                    "u10m" : { "name" : "10 m above ground U-Component of Wind", "unit": "m/s"},
                                    "v10m" : { "name" : "10 m above ground V-Component of Wind", "unit": "m/s"},
                                    "t2m" : { "name" : "2 m above ground Temperature", "unit": "C"},
                                    "slp" : { "name" : "mean sea level Pressure Reduced to MSL", "unit": "Pa"},
                                    "psfc" : { "name" : "mean sea level sea level pressure -  METAR formulation", "unit": "Pa"},
                                    "terrain" : { "name" : "surface Geopotential Height", "unit": "gpm"},
                                    "sbcape" : { "name" : "surface Convective Available Potential Energy", "unit": "J/kg"},
                                    "sbcin" : { "name" : "surface Convective Inhibition", "unit": "J/kg"},
                                    "pw" : { "name" : "surface Precipitable Water", "unit": "kg/m^2"},
                                    "precip" : { "name" : "surface Total Precipitation", "unit": "kg/m^2"},
                                    "acpcp" : { "name" : "surface Convective Precipitation", "unit": "kg/m^2"},
                                    "tveg1" : { "name" : "surface Vegetation Temperature p1", "unit": "C"},
                                    "tveg2" : { "name" : "surface Vegetation Temperature p2", "unit": "C"},
                                    "tveg3" : { "name" : "surface Vegetation Temperature p3", "unit": "C"},
                                    "tveg4" : { "name" : "surface Vegetation Temperature p4", "unit": "C"},
                                    "lhtfl" : { "name" : "surface Latent Heat Net Flux", "unit": "W/m^2"}, 
                                    "shtfl" : { "name" : "surface Sensible Heat Net Flux", "unit": "W/m^2"},
                                    "nswrs" : { "name" : "surface Net Short-Wave Radiation Flux (Surface)", "unit": "W/m^2"},
                                    "nlwrs" : { "name" : "surface Net Long-Wave Radiation Flux (Surface)", "unit": "W/m^2"},
                                    "albdo" : { "name" : "surface Albedo", "unit": "%"},
                                    "ulwrf" : { "name" : "surface Upward Long-Wave Rad. Flux", "unit": "W/m^2"}, 
                                    "wtmpil" : { "name" : "surface Water Temperature", "unit": "C"}, 
                                    "dpt" : { "name" : "2 m above ground Dew Point Temperature", "unit": "C"},
                                    "soilm1"  :{ "name" :"surface soil moisture patch 1", "unit": "m^3/m^3"},
                                    "soilm2" : { "name" : "surface soil moisture patch 2", "unit": "m^3/m^3"}, 
                                    "soilm3" : { "name" : "surface soil moisture patch 3", "unit": "m^3/m^3"},
                                    "soilm4" : { "name" : "surface soil moisture patch 4", "unit": "m^3/m^3"},
                                    "hpbl" : { "name" : "surface Planetary Boundary Layer Height", "unit": "m"}, 
                                    "clmr" : { "name" : "Cloud Mixing Ratio", "unit": "kg/kg"},
                                    "vapmrt" : { "name" : "Vapor Mix Ratio", "unit": "g/kg"},
                                    "epot" : { "name" : "Pseudo-Adiabatic Potential Temperature (or Equivalent Potential Temperature)", "unit": "C"},
                                    "pres" : { "name" : "surface Pressure", "unit": "Pa"},
                                    "ndvi1" : { "name" : "surface Normalized Differential Vegetation Index (NDVI) patch 1", "unit": "Numeric"},
                                    "ndvi2" : { "name" : "surface Normalized Differential Vegetation Index (NDVI) patch 2", "unit": "Numeric"},
                                    "ndvi3" : { "name" : "surface Normalized Differential Vegetation Index (NDVI) patch 3", "unit": "Numeric"},
                                    "ndvi4" : { "name" : "surface Normalized Differential Vegetation Index (NDVI) patch 4", "unit": "Numeric"},
                                    "lai1" : { "name" : "surface green leaf area index 1", "unit": "Numeric"},
                                    "lai2" : { "name" : "surface green leaf area index 2", "unit": "Numeric"},
                                    "lai3" : { "name" : "surface green leaf area index 3", "unit": "Numeric"},
                                    "lai4" : { "name" : "surface green leaf area index 4", "unit": "Numeric"},
                                    "hcdc" : { "name" : "surface High Cloud Cover", "unit": "%"},
                                    "mcdc" : { "name" : "surface Medium Cloud Cover", "unit": "%"},
                               },
                    "area"    : {
                                    "minlat" :    -45,
                                    "maxlat" :     10,
                                    "minlon" :    277,
                                    "maxlon" :    332,
                                    "dx"     :  20000
                                },

                    "transform" : {
                                    "precip"  :       "/4",
                                    "t"       :  "-273.15",
                                    "rh"      :     "*100",
                                    "omega"   :      "*10",
                                    "t2m"     :  "-273.15",
                                    "wtmpil"  :  "-273.15",
                                    "dpt"     :  "-273.15",
                                    "epot"    :  "-273.15"                                                                     
                                },

                    "file"    : {
                                    "name"   :     "BRAMS_ams_08km_{}_{}.grib2",
                                    "format" :     "grib2"
                                },
            "server":   {
                            "ftp"    :     "https://dataserver.cptec.inpe.br/dataserver_modelos/brams"
            }
    
        } 