# generated by datamodel-codegen:
#   filename:  software_directory/ml/exabyteml.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class Name(Enum):
    exabyteml = "exabyteml"


class Summary(Enum):
    exabyte_machine_learning_engine = "exabyte machine learning engine"


class Version(Enum):
    field_0_2_0 = "0.2.0"


class ExabyteMachineLearningEngineSchema(BaseModel):
    name: Optional[Name] = None
    summary: Optional[Summary] = None
    version: Optional[Version] = None
