"""This file was generated by xsdata, v25.4, on 2025-05-21 12:08:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

__NAMESPACE__ = "http://colorexchangeformat.com/CxF3-core"


@dataclass
class ColorHtml:
    """
    ColorSpace type that holds the encoded RGB string used for previewing a color
    in html syntax.
    """

    class Meta:
        name = "ColorHTML"
        namespace = "http://colorexchangeformat.com/CxF3-core"

    name: None | str = field(
        default=None,
        metadata={
            "name": "Name",
            "type": "Attribute",
        },
    )
    html: None | str = field(
        default=None,
        metadata={
            "name": "HTML",
            "type": "Attribute",
            "required": True,
        },
    )
    color_specification: None | str = field(
        default=None,
        metadata={
            "name": "ColorSpecification",
            "type": "Attribute",
            "required": True,
        },
    )
