"""This file was generated by xsdata, v25.4, on 2025-05-21 12:08:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://colorexchangeformat.com/CxF3-core"


class EdensityFilterType(Enum):
    """
    Enumeration of various density filters, such as Red, Green, etc.
    """

    VISUAL = "Visual"
    CYAN = "Cyan"
    MAGENTA = "Magenta"
    YELLOW = "Yellow"
    BLACK = "Black"
    RED = "Red"
    GREEN = "Green"
    BLUE = "Blue"
    A = "A"
    B = "B"
