# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61970/base/generation/production/PowerElectronicsUnit.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61970.base.core import Equipment_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_Equipment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRzepben/protobuf/cim/iec61970/base/generation/production/PowerElectronicsUnit.proto\x12\x37zepben.protobuf.cim.iec61970.base.generation.production\x1a\x36zepben/protobuf/cim/iec61970/base/core/Equipment.proto\"\x99\x01\n\x14PowerElectronicsUnit\x12=\n\x02\x65q\x18\x01 \x01(\x0b\x32\x31.zepben.protobuf.cim.iec61970.base.core.Equipment\x12\x0c\n\x04maxP\x18\x02 \x01(\x05\x12\x0c\n\x04minP\x18\x03 \x01(\x05\x12&\n\x1epowerElectronicsConnectionMRID\x18\x04 \x01(\tB?\n;com.zepben.protobuf.cim.iec61970.base.generation.productionP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.cim.iec61970.base.generation.production.PowerElectronicsUnit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n;com.zepben.protobuf.cim.iec61970.base.generation.productionP\001'
  _globals['_POWERELECTRONICSUNIT']._serialized_start=200
  _globals['_POWERELECTRONICSUNIT']._serialized_end=353
# @@protoc_insertion_point(module_scope)
