
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-15T11:15:05+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "54663f072ef4dd93011955472b72e37178b6c9a5",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
