# coding: utf-8

"""
    aind-slims-service

     ## aind-slims-service  Service to pull data from SLIMS.  

    The version of the OpenAPI document: 0.3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slims_service_async_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_aind_instrument(self) -> None:
        """Test case for get_aind_instrument

        Get Aind Instrument
        """
        pass

    async def test_get_ecephys_sessions(self) -> None:
        """Test case for get_ecephys_sessions

        Get Ecephys Sessions
        """
        pass

    async def test_get_histology_data(self) -> None:
        """Test case for get_histology_data

        Get Histology Data
        """
        pass

    async def test_get_smartspim_imaging(self) -> None:
        """Test case for get_smartspim_imaging

        Get Smartspim Imaging
        """
        pass

    async def test_get_viral_injections(self) -> None:
        """Test case for get_viral_injections

        Get Viral Injections
        """
        pass

    async def test_get_water_restriction_data(self) -> None:
        """Test case for get_water_restriction_data

        Get Water Restriction Data
        """
        pass


if __name__ == '__main__':
    unittest.main()
