# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .signatures_create_response_data import SignaturesCreateResponseDataParams
from .signatures_create_response_error import SignaturesCreateResponseErrorParams
from .signatures_create_response_links import SignaturesCreateResponseLinksParams
from .signatures_create_response_meta import SignaturesCreateResponseMetaParams


class SignaturesCreateResponseParams(typing_extensions.TypedDict):
    meta: typing_extensions.NotRequired[SignaturesCreateResponseMetaParams]
    data: typing_extensions.NotRequired[SignaturesCreateResponseDataParams]
    error: typing_extensions.NotRequired[SignaturesCreateResponseErrorParams]
    links: typing_extensions.NotRequired[SignaturesCreateResponseLinksParams]
