from setuptools import setup, find_packages

setup(
    name="askpandas",
    version="0.1.1",
    description="AI-powered data engineering and analytics assistant for querying CSV data using natural language—locally and intelligently",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Md Irfan Ali",
    author_email="irfanali29@hotmail.com",
    url="https://github.com/irfanalidv/AskPandas",
    packages=find_packages(),
    install_requires=[
        "pandas>=1.5.0",
        "numpy>=1.23.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.12.0",
        "requests>=2.28.0",
        "transformers>=4.30.0",
        "torch>=2.0.0",
        "faker>=18.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=22.0.0",
            "flake8>=5.0.0",
            "mypy>=1.0.0",
        ],
        "full": [
            "jupyter>=1.0.0",
            "ipywidgets>=8.0.0",
            "plotly>=5.0.0",
            "bokeh>=3.0.0",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Text Processing :: Linguistic",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    keywords=[
        "data-analysis",
        "pandas",
        "ai",
        "natural-language",
        "csv",
        "data-science",
        "machine-learning",
        "llm",
        "ollama",
        "huggingface",
    ],
    project_urls={
        "Bug Reports": "https://github.com/irfanalidv/AskPandas/issues",
        "Source": "https://github.com/irfanalidv/AskPandas",
        "Documentation": "https://github.com/irfanalidv/AskPandas#readme",
    },
    include_package_data=True,
    zip_safe=False,
)
