# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07nbqueue\"\xdc\x02\n\x10\x43reateJobRequest\x12\x15\n\rnotebook_file\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x0f\n\x07project\x18\x03 \x01(\t\x12\x18\n\x10nbqueue_job_name\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\x11\n\tconda_env\x18\x06 \x01(\t\x12\x13\n\x0boutput_path\x18\x07 \x01(\t\x12\x0b\n\x03\x63pu\x18\x08 \x01(\t\x12\x0b\n\x03ram\x18\t \x01(\t\x12\x0b\n\x03uid\x18\n \x01(\t\x12\x0b\n\x03gid\x18\x0b \x01(\t\x12\x11\n\tnamespace\x18\x0c \x01(\t\x12\x15\n\ross_node_pool\x18\r \x01(\t\x12\x17\n\x0foss_tolerations\x18\x0e \x01(\t\x12\x1b\n\x13oss_service_account\x18\x0f \x01(\t\x12\x16\n\x0e\x65\x66s_mount_path\x18\x10 \x01(\t\x12\x14\n\x0c\x65\x66s_pvc_name\x18\x11 \x01(\t\"c\n\x11\x43reateJobResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x16\n\x0ekubectl_output\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"5\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\"\xcc\x01\n\x11JobStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08job_json\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x13\n\x0b\x61\x63tive_pods\x18\x05 \x01(\x05\x12\x16\n\x0esucceeded_pods\x18\x06 \x01(\x05\x12\x13\n\x0b\x66\x61iled_pods\x18\x07 \x01(\x05\x12\x12\n\nstart_time\x18\x08 \x01(\t\x12\x17\n\x0f\x63ompletion_time\x18\t \x01(\t2\x98\x01\n\x0eNBQueueService\x12\x42\n\tCreateJob\x12\x19.nbqueue.CreateJobRequest\x1a\x1a.nbqueue.CreateJobResponse\x12\x42\n\tJobStatus\x12\x19.nbqueue.JobStatusRequest\x1a\x1a.nbqueue.JobStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEJOBREQUEST']._serialized_start=27
  _globals['_CREATEJOBREQUEST']._serialized_end=375
  _globals['_CREATEJOBRESPONSE']._serialized_start=377
  _globals['_CREATEJOBRESPONSE']._serialized_end=476
  _globals['_JOBSTATUSREQUEST']._serialized_start=478
  _globals['_JOBSTATUSREQUEST']._serialized_end=531
  _globals['_JOBSTATUSRESPONSE']._serialized_start=534
  _globals['_JOBSTATUSRESPONSE']._serialized_end=738
  _globals['_NBQUEUESERVICE']._serialized_start=741
  _globals['_NBQUEUESERVICE']._serialized_end=893
# @@protoc_insertion_point(module_scope)
