"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from langcache.errors import LangCacheError
from langcache.models import authenticationerroruri as models_authenticationerroruri
from langcache.types import BaseModel
from typing import Optional


class AuthenticationErrorResponseContentData(BaseModel):
    title: str
    r"""A short summary of the problem type."""

    type: models_authenticationerroruri.AuthenticationErrorURI

    status: Optional[int] = 401
    r"""The HTTP status code generated by the origin server."""

    detail: Optional[str] = None
    r"""An explanation specific to this problem."""


class AuthenticationErrorResponseContent(LangCacheError):
    data: AuthenticationErrorResponseContentData

    def __init__(
        self,
        data: AuthenticationErrorResponseContentData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
