# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .automation_response_data_status import AutomationResponseDataStatus
from .automation_response_data_trigger import AutomationResponseDataTrigger
from .automation_response_data_workflow_item import AutomationResponseDataWorkflowItem


class AutomationResponseData(UncheckedBaseModel):
    id: str
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    trigger: AutomationResponseDataTrigger
    workflow: typing.List[AutomationResponseDataWorkflowItem]
    status: AutomationResponseDataStatus
    created: dt.datetime
    updated: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
