# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .file_list_response_data_item import FileListResponseDataItem
from .file_list_response_error import FileListResponseError
from .file_list_response_links import FileListResponseLinks
from .file_list_response_meta import FileListResponseMeta


class FileListResponse(UncheckedBaseModel):
    meta: typing.Optional[FileListResponseMeta] = None
    data: typing.Optional[typing.List[FileListResponseDataItem]] = None
    error: typing.Optional[FileListResponseError] = None
    links: typing.Optional[FileListResponseLinks] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
