# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 0.0.97

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.vpsv1_docker_manager_project_resource import VPSV1DockerManagerProjectResource

class TestVPSV1DockerManagerProjectResource(unittest.TestCase):
    """VPSV1DockerManagerProjectResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VPSV1DockerManagerProjectResource:
        """Test VPSV1DockerManagerProjectResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VPSV1DockerManagerProjectResource`
        """
        model = VPSV1DockerManagerProjectResource()
        if include_optional:
            return VPSV1DockerManagerProjectResource(
                name = 'my-project',
                status = 'running(2)',
                state = 'running',
                path = '/docker/my-project/docker-compose.yaml'
            )
        else:
            return VPSV1DockerManagerProjectResource(
        )
        """

    def testVPSV1DockerManagerProjectResource(self):
        """Test VPSV1DockerManagerProjectResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
