
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-14T16:32:04-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "11619819ff7101680483bf3c50b4087e170e11ad",
 "version": "2.68.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
