
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-15T10:17:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1551d01e7ec9ba140b9bf0dbd88ebc15bdcf4e27",
 "version": "0.35.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
