# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61968/assetinfo/ShortCircuitTest.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61968.assetinfo import TransformerTest_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61968_dot_assetinfo_dot_TransformerTest__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=zepben/protobuf/cim/iec61968/assetinfo/ShortCircuitTest.proto\x12&zepben.protobuf.cim.iec61968.assetinfo\x1a<zepben/protobuf/cim/iec61968/assetinfo/TransformerTest.proto\"\xad\x02\n\x10ShortCircuitTest\x12\x43\n\x02tt\x18\x01 \x01(\x0b\x32\x37.zepben.protobuf.cim.iec61968.assetinfo.TransformerTest\x12\x0f\n\x07\x63urrent\x18\x02 \x01(\x01\x12\x18\n\x10\x65nergisedEndStep\x18\x03 \x01(\x05\x12\x17\n\x0fgroundedEndStep\x18\x04 \x01(\x05\x12\x18\n\x10leakageImpedance\x18\x05 \x01(\x01\x12\x1c\n\x14leakageImpedanceZero\x18\x06 \x01(\x01\x12\x0c\n\x04loss\x18\x07 \x01(\x05\x12\x10\n\x08lossZero\x18\x08 \x01(\x05\x12\r\n\x05power\x18\t \x01(\x05\x12\x0f\n\x07voltage\x18\n \x01(\x01\x12\x18\n\x10voltageOhmicPart\x18\x0b \x01(\x01\x42.\n*com.zepben.protobuf.cim.iec61968.assetinfoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*com.zepben.protobuf.cim.iec61968.assetinfoP\001'
  _globals['_SHORTCIRCUITTEST']._serialized_start=168
  _globals['_SHORTCIRCUITTEST']._serialized_end=469
# @@protoc_insertion_point(module_scope)
