"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .grouptype import GroupType
from glean.api_client.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GroupTypedDict(TypedDict):
    type: GroupType
    r"""The type of user group"""
    id: str
    r"""A unique identifier for the group. May be the same as name."""
    name: NotRequired[str]
    r"""Name of the group."""


class Group(BaseModel):
    type: GroupType
    r"""The type of user group"""

    id: str
    r"""A unique identifier for the group. May be the same as name."""

    name: Optional[str] = None
    r"""Name of the group."""
