# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from eigenda.grpc.relay import relay_pb2 as relay_dot_relay__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in relay/relay_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RelayStub(object):
    """Relay is a service that provides access to public relay functionality."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBlob = channel.unary_unary(
            "/relay.Relay/GetBlob",
            request_serializer=relay_dot_relay__pb2.GetBlobRequest.SerializeToString,
            response_deserializer=relay_dot_relay__pb2.GetBlobReply.FromString,
            _registered_method=True,
        )
        self.GetChunks = channel.unary_unary(
            "/relay.Relay/GetChunks",
            request_serializer=relay_dot_relay__pb2.GetChunksRequest.SerializeToString,
            response_deserializer=relay_dot_relay__pb2.GetChunksReply.FromString,
            _registered_method=True,
        )


class RelayServicer(object):
    """Relay is a service that provides access to public relay functionality."""

    def GetBlob(self, request, context):
        """GetBlob retrieves a blob stored by the relay."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetChunks(self, request, context):
        """GetChunks retrieves chunks from blobs stored by the relay."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetBlob": grpc.unary_unary_rpc_method_handler(
            servicer.GetBlob,
            request_deserializer=relay_dot_relay__pb2.GetBlobRequest.FromString,
            response_serializer=relay_dot_relay__pb2.GetBlobReply.SerializeToString,
        ),
        "GetChunks": grpc.unary_unary_rpc_method_handler(
            servicer.GetChunks,
            request_deserializer=relay_dot_relay__pb2.GetChunksRequest.FromString,
            response_serializer=relay_dot_relay__pb2.GetChunksReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("relay.Relay", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("relay.Relay", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Relay(object):
    """Relay is a service that provides access to public relay functionality."""

    @staticmethod
    def GetBlob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/relay.Relay/GetBlob",
            relay_dot_relay__pb2.GetBlobRequest.SerializeToString,
            relay_dot_relay__pb2.GetBlobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetChunks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/relay.Relay/GetChunks",
            relay_dot_relay__pb2.GetChunksRequest.SerializeToString,
            relay_dot_relay__pb2.GetChunksReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
