# This file was auto-generated by Fern from our API Definition.

import typing

ClassificationConfigBaseProcessor = typing.Union[
    typing.Literal["classifier_performance", "classifier_light"], typing.Any
]
