# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rbt/cloud/v1alpha1/logs/logs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rbt.v1alpha1 import options_pb2 as rbt_dot_v1alpha1_dot_options__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"rbt/cloud/v1alpha1/logs/logs.proto\x12\x17rbt.cloud.v1alpha1.logs\x1a\x1arbt/v1alpha1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n\tLogRecord\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0c\x63onsensus_id\x18\x03 \x01(\tH\x00\x12\x17\n\rconfig_run_id\x18\x05 \x01(\tH\x00\x12\x1c\n\x0frevision_number\x18\x06 \x01(\rH\x01\x88\x01\x01\x12\x0c\n\x04text\x18\x04 \x01(\tB\x08\n\x06sourceB\x12\n\x10_revision_number\",\n\x0f\x41pplicationLogs:\x04\x82\xb5\x18\x00J\x04\x08\x01\x10\x02R\rconsensus_ids\"\x0f\n\rEnsureRequest\"\x10\n\x0e\x45nsureResponse\".\n\x18RegisterConsensusRequestJ\x04\x08\x01\x10\x02R\x0c\x63onsensus_id\"\x1b\n\x19RegisterConsensusResponse\"D\n\rIngestRequest\x12\x33\n\x07records\x18\x01 \x03(\x0b\x32\".rbt.cloud.v1alpha1.logs.LogRecord\"\x10\n\x0eIngestResponse\"7\n\x0bLogsRequest\x12\x0e\n\x06\x66ollow\x18\x01 \x01(\x08\x12\x18\n\x10revision_numbers\x18\x02 \x03(\r\"C\n\x0cLogsResponse\x12\x33\n\x07records\x18\x01 \x03(\x0b\x32\".rbt.cloud.v1alpha1.logs.LogRecord\"\x10\n\x0e\x41rchiveRequest\"\x11\n\x0f\x41rchiveResponse2\xe1\x02\n\x16\x41pplicationLogsMethods\x12\x61\n\x06\x45nsure\x12&.rbt.cloud.v1alpha1.logs.EnsureRequest\x1a\'.rbt.cloud.v1alpha1.logs.EnsureResponse\"\x06\x82\xb5\x18\x02\x12\x00\x12\x82\x01\n\x11RegisterConsensus\x12\x31.rbt.cloud.v1alpha1.logs.RegisterConsensusRequest\x1a\x32.rbt.cloud.v1alpha1.logs.RegisterConsensusResponse\"\x06\x82\xb5\x18\x02\x12\x00\x12_\n\x04Logs\x12$.rbt.cloud.v1alpha1.logs.LogsRequest\x1a%.rbt.cloud.v1alpha1.logs.LogsResponse\"\x08\x82\xb5\x18\x04\n\x02\x18\x02\x30\x01\x32j\n\tLogsProxy\x12]\n\x06Ingest\x12&.rbt.cloud.v1alpha1.logs.IngestRequest\x1a\'.rbt.cloud.v1alpha1.logs.IngestResponse\"\x00(\x01\x62\x06proto3')



_LOGRECORD = DESCRIPTOR.message_types_by_name['LogRecord']
_APPLICATIONLOGS = DESCRIPTOR.message_types_by_name['ApplicationLogs']
_ENSUREREQUEST = DESCRIPTOR.message_types_by_name['EnsureRequest']
_ENSURERESPONSE = DESCRIPTOR.message_types_by_name['EnsureResponse']
_REGISTERCONSENSUSREQUEST = DESCRIPTOR.message_types_by_name['RegisterConsensusRequest']
_REGISTERCONSENSUSRESPONSE = DESCRIPTOR.message_types_by_name['RegisterConsensusResponse']
_INGESTREQUEST = DESCRIPTOR.message_types_by_name['IngestRequest']
_INGESTRESPONSE = DESCRIPTOR.message_types_by_name['IngestResponse']
_LOGSREQUEST = DESCRIPTOR.message_types_by_name['LogsRequest']
_LOGSRESPONSE = DESCRIPTOR.message_types_by_name['LogsResponse']
_ARCHIVEREQUEST = DESCRIPTOR.message_types_by_name['ArchiveRequest']
_ARCHIVERESPONSE = DESCRIPTOR.message_types_by_name['ArchiveResponse']
LogRecord = _reflection.GeneratedProtocolMessageType('LogRecord', (_message.Message,), {
  'DESCRIPTOR' : _LOGRECORD,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.LogRecord)
  })
_sym_db.RegisterMessage(LogRecord)

ApplicationLogs = _reflection.GeneratedProtocolMessageType('ApplicationLogs', (_message.Message,), {
  'DESCRIPTOR' : _APPLICATIONLOGS,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.ApplicationLogs)
  })
_sym_db.RegisterMessage(ApplicationLogs)

EnsureRequest = _reflection.GeneratedProtocolMessageType('EnsureRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENSUREREQUEST,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.EnsureRequest)
  })
_sym_db.RegisterMessage(EnsureRequest)

EnsureResponse = _reflection.GeneratedProtocolMessageType('EnsureResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENSURERESPONSE,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.EnsureResponse)
  })
_sym_db.RegisterMessage(EnsureResponse)

RegisterConsensusRequest = _reflection.GeneratedProtocolMessageType('RegisterConsensusRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCONSENSUSREQUEST,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.RegisterConsensusRequest)
  })
_sym_db.RegisterMessage(RegisterConsensusRequest)

RegisterConsensusResponse = _reflection.GeneratedProtocolMessageType('RegisterConsensusResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCONSENSUSRESPONSE,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.RegisterConsensusResponse)
  })
_sym_db.RegisterMessage(RegisterConsensusResponse)

IngestRequest = _reflection.GeneratedProtocolMessageType('IngestRequest', (_message.Message,), {
  'DESCRIPTOR' : _INGESTREQUEST,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.IngestRequest)
  })
_sym_db.RegisterMessage(IngestRequest)

IngestResponse = _reflection.GeneratedProtocolMessageType('IngestResponse', (_message.Message,), {
  'DESCRIPTOR' : _INGESTRESPONSE,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.IngestResponse)
  })
_sym_db.RegisterMessage(IngestResponse)

LogsRequest = _reflection.GeneratedProtocolMessageType('LogsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGSREQUEST,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.LogsRequest)
  })
_sym_db.RegisterMessage(LogsRequest)

LogsResponse = _reflection.GeneratedProtocolMessageType('LogsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGSRESPONSE,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.LogsResponse)
  })
_sym_db.RegisterMessage(LogsResponse)

ArchiveRequest = _reflection.GeneratedProtocolMessageType('ArchiveRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARCHIVEREQUEST,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.ArchiveRequest)
  })
_sym_db.RegisterMessage(ArchiveRequest)

ArchiveResponse = _reflection.GeneratedProtocolMessageType('ArchiveResponse', (_message.Message,), {
  'DESCRIPTOR' : _ARCHIVERESPONSE,
  '__module__' : 'rbt.cloud.v1alpha1.logs.logs_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.logs.ArchiveResponse)
  })
_sym_db.RegisterMessage(ArchiveResponse)

_APPLICATIONLOGSMETHODS = DESCRIPTOR.services_by_name['ApplicationLogsMethods']
_LOGSPROXY = DESCRIPTOR.services_by_name['LogsProxy']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPLICATIONLOGS._options = None
  _APPLICATIONLOGS._serialized_options = b'\202\265\030\000'
  _APPLICATIONLOGSMETHODS.methods_by_name['Ensure']._options = None
  _APPLICATIONLOGSMETHODS.methods_by_name['Ensure']._serialized_options = b'\202\265\030\002\022\000'
  _APPLICATIONLOGSMETHODS.methods_by_name['RegisterConsensus']._options = None
  _APPLICATIONLOGSMETHODS.methods_by_name['RegisterConsensus']._serialized_options = b'\202\265\030\002\022\000'
  _APPLICATIONLOGSMETHODS.methods_by_name['Logs']._options = None
  _APPLICATIONLOGSMETHODS.methods_by_name['Logs']._serialized_options = b'\202\265\030\004\n\002\030\002'
  _LOGRECORD._serialized_start=125
  _LOGRECORD._serialized_end=320
  _APPLICATIONLOGS._serialized_start=322
  _APPLICATIONLOGS._serialized_end=366
  _ENSUREREQUEST._serialized_start=368
  _ENSUREREQUEST._serialized_end=383
  _ENSURERESPONSE._serialized_start=385
  _ENSURERESPONSE._serialized_end=401
  _REGISTERCONSENSUSREQUEST._serialized_start=403
  _REGISTERCONSENSUSREQUEST._serialized_end=449
  _REGISTERCONSENSUSRESPONSE._serialized_start=451
  _REGISTERCONSENSUSRESPONSE._serialized_end=478
  _INGESTREQUEST._serialized_start=480
  _INGESTREQUEST._serialized_end=548
  _INGESTRESPONSE._serialized_start=550
  _INGESTRESPONSE._serialized_end=566
  _LOGSREQUEST._serialized_start=568
  _LOGSREQUEST._serialized_end=623
  _LOGSRESPONSE._serialized_start=625
  _LOGSRESPONSE._serialized_end=692
  _ARCHIVEREQUEST._serialized_start=694
  _ARCHIVEREQUEST._serialized_end=710
  _ARCHIVERESPONSE._serialized_start=712
  _ARCHIVERESPONSE._serialized_end=729
  _APPLICATIONLOGSMETHODS._serialized_start=732
  _APPLICATIONLOGSMETHODS._serialized_end=1085
  _LOGSPROXY._serialized_start=1087
  _LOGSPROXY._serialized_end=1193
# @@protoc_insertion_point(module_scope)
