# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["Integration"]


class Integration(BaseModel):
    id: str

    connector_name: Literal[
        "accelo",
        "acme-apikey",
        "acme-oauth2",
        "adobe",
        "adyen",
        "aircall",
        "airtable",
        "amazon",
        "apaleo",
        "apollo",
        "asana",
        "attio",
        "auth0",
        "autodesk",
        "aws",
        "bamboohr",
        "basecamp",
        "battlenet",
        "bigcommerce",
        "bitbucket",
        "bitly",
        "blackbaud",
        "boldsign",
        "box",
        "braintree",
        "brex",
        "calendly",
        "clickup",
        "close",
        "coda",
        "confluence",
        "contentful",
        "contentstack",
        "copper",
        "coros",
        "datev",
        "deel",
        "dialpad",
        "digitalocean",
        "discord",
        "docusign",
        "dropbox",
        "ebay",
        "egnyte",
        "envoy",
        "eventbrite",
        "exist",
        "facebook",
        "factorial",
        "figma",
        "finch",
        "firebase",
        "fitbit",
        "foreceipt",
        "fortnox",
        "freshbooks",
        "front",
        "github",
        "gitlab",
        "gong",
        "google-calendar",
        "google-docs",
        "google-drive",
        "google-mail",
        "google-sheet",
        "gorgias",
        "grain",
        "greenhouse",
        "gumroad",
        "gusto",
        "harvest",
        "heron",
        "highlevel",
        "hubspot",
        "instagram",
        "intercom",
        "jira",
        "keap",
        "lever",
        "linear",
        "linkedin",
        "linkhut",
        "lunchmoney",
        "mailchimp",
        "mercury",
        "merge",
        "miro",
        "monday",
        "moota",
        "mural",
        "namely",
        "nationbuilder",
        "netsuite",
        "notion",
        "odoo",
        "okta",
        "onebrick",
        "openledger",
        "osu",
        "oura",
        "outreach",
        "pagerduty",
        "pandadoc",
        "payfit",
        "paypal",
        "pennylane",
        "pinterest",
        "pipedrive",
        "plaid",
        "podium",
        "postgres",
        "productboard",
        "qualtrics",
        "quickbooks",
        "ramp",
        "reddit",
        "sage",
        "salesforce",
        "salesloft",
        "saltedge",
        "segment",
        "servicem8",
        "servicenow",
        "sharepoint",
        "sharepoint-onprem",
        "shopify",
        "signnow",
        "slack",
        "smartsheet",
        "snowflake",
        "splitwise",
        "spotify",
        "squarespace",
        "squareup",
        "stackexchange",
        "strava",
        "stripe",
        "teamwork",
        "teller",
        "ticktick",
        "timely",
        "todoist",
        "toggl",
        "tremendous",
        "tsheetsteam",
        "tumblr",
        "twenty",
        "twinfield",
        "twitch",
        "twitter",
        "typeform",
        "uber",
        "venmo",
        "vimeo",
        "wakatime",
        "wealthbox",
        "webflow",
        "whoop",
        "wise",
        "wordpress",
        "wrike",
        "xero",
        "yahoo",
        "yandex",
        "yodlee",
        "zapier",
        "zendesk",
        "zenefits",
        "zoho",
        "zoho-desk",
        "zoom",
    ]

    created_at: str

    external: Union[str, float, bool, Dict[str, object], List[object], None] = None

    name: str

    standard: Union[str, float, bool, Dict[str, object], List[object], None] = None

    updated_at: str

    auth_type: Optional[str] = None

    category: Optional[str] = None

    logo_url: Optional[str] = None

    platforms: Optional[List[Literal["web", "mobile", "desktop"]]] = None

    stage: Optional[Literal["alpha", "beta", "ga"]] = None

    version: Optional[str] = None
