# This file is generated by translate_mathematica.py
# Do not edit this file directly
# Instead, edit amps_mathematica.m and run translate_mathematica.py
# to regenerate this file
#
# This file contains the translation of Mathematica code to Python
# using the sympy library
#
gT = Symbol('gT')
m23 = Symbol('m23')
mf2 = Symbol('mf2')
mpiplus = Symbol('mpiplus')
ma = Symbol('ma')
metap = Symbol('metap')
m12 = Symbol('m12')
cG = Symbol('cG')
kappad = Symbol('kappad')
deltaI = Symbol('deltaI')
thetaprpi = Symbol('thetaprpi')
kappau = Symbol('kappau')
thpiALP = Symbol('thpiALP')
thetaALP = Symbol('thetaALP')
thetaprALP = Symbol('thetaprALP')
Gammaf2 = Symbol('Gammaf2')
UnitStep = Function('UnitStep')
e = -gT**2*(m23**2*(mf2**2 - 2*mpiplus**2)*(ma**2 + metap**2 - mf2**2) + m23*(-ma**4*(mf2**2 - 2*mpiplus**2) + ma**2*(2*metap**2*(mf2**2 - 2*mpiplus**2) + mf2**4 + 2*mf2**2*mpiplus**2) - metap**4*(mf2**2 - 2*mpiplus**2) + metap**2*(mf2**4 + 2*mf2**2*mpiplus**2) + 2*mf2**4*(-3*m12 + mpiplus**2)) - 2*mf2**2*(3*m12**2*mf2**2 - 3*m12*mf2**2*(ma**2 + metap**2 + 2*mpiplus**2) + 2*ma**4*mpiplus**2 + ma**2*(metap**2*(3*mf2**2 - 4*mpiplus**2) + mf2**2*mpiplus**2) + mpiplus**2*(2*metap**4 + metap**2*mf2**2 + 3*mf2**2*mpiplus**2)))*(cG*kappad*(-3*deltaI*thetaprpi + sqrt(3)) + cG*kappau*(3*deltaI*thetaprpi + sqrt(3)) + 3*deltaI*thetaprpi*thpiALP + sqrt(2)*thetaALP + thetaprALP)*UnitStep(m23 - (Gammaf2 - mf2)**2)/(144*mf2**4*(-m23 + mf2*(-I*Gammaf2 + mf2)))