# This file is generated by translate_mathematica.py
# Do not edit this file directly
# Instead, edit amps_mathematica.m and run translate_mathematica.py
# to regenerate this file
#
# This file contains the translation of Mathematica code to Python
# using the sympy library
#
mrhoplus = Symbol('mrhoplus')
cG = Symbol('cG')
kappad = Symbol('kappad')
kappau = Symbol('kappau')
thpiALP = Symbol('thpiALP')
m12 = Symbol('m12')
m23 = Symbol('m23')
ma = Symbol('ma')
mpi0 = Symbol('mpi0')
Gammarhoplus = Symbol('Gammarhoplus')
F0 = Symbol('F0')
e = mrhoplus**2*(cG*(kappad - kappau) - thpiALP)*(2*m12**2 + 2*m12*m23 - 3*m12*(ma**2 + 3*mpi0**2 + I*mrhoplus*(Gammarhoplus + I*mrhoplus)) + 2*m23**2 - 2*m23*(ma**2 + 3*mpi0**2) + (ma**2 + 3*mpi0**2)*(ma**2 + 3*mpi0**2 + I*mrhoplus*(Gammarhoplus + I*mrhoplus)))/(2*F0**2*(m23 + I*mrhoplus*(Gammarhoplus + I*mrhoplus))*(-I*Gammarhoplus*mrhoplus + m12 + m23 - ma**2 - 3*mpi0**2 + mrhoplus**2))