# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .files_list_response_data_item import FilesListResponseDataItemParams
from .files_list_response_error import FilesListResponseErrorParams
from .files_list_response_links import FilesListResponseLinksParams
from .files_list_response_meta import FilesListResponseMetaParams


class FilesListResponseParams(typing_extensions.TypedDict):
    meta: typing_extensions.NotRequired[FilesListResponseMetaParams]
    data: typing_extensions.NotRequired[typing.Sequence[FilesListResponseDataItemParams]]
    error: typing_extensions.NotRequired[FilesListResponseErrorParams]
    links: typing_extensions.NotRequired[FilesListResponseLinksParams]
