# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .files_create_response_data import FilesCreateResponseDataParams
from .files_create_response_error import FilesCreateResponseErrorParams
from .files_create_response_links import FilesCreateResponseLinksParams
from .files_create_response_meta import FilesCreateResponseMetaParams


class FilesCreateResponseParams(typing_extensions.TypedDict):
    meta: typing_extensions.NotRequired[FilesCreateResponseMetaParams]
    data: typing_extensions.NotRequired[FilesCreateResponseDataParams]
    error: typing_extensions.NotRequired[FilesCreateResponseErrorParams]
    links: typing_extensions.NotRequired[FilesCreateResponseLinksParams]
