# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .files_update_response_data import FilesUpdateResponseDataParams
from .files_update_response_error import FilesUpdateResponseErrorParams
from .files_update_response_links import FilesUpdateResponseLinksParams
from .files_update_response_meta import FilesUpdateResponseMetaParams


class FilesUpdateResponseParams(typing_extensions.TypedDict):
    meta: typing_extensions.NotRequired[FilesUpdateResponseMetaParams]
    data: typing_extensions.NotRequired[FilesUpdateResponseDataParams]
    error: typing_extensions.NotRequired[FilesUpdateResponseErrorParams]
    links: typing_extensions.NotRequired[FilesUpdateResponseLinksParams]
