# coding: utf-8

"""
    aind-slims-service

     ## aind-slims-service  Service to pull data from SLIMS.  

    The version of the OpenAPI document: 0.3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slims_service_client.models.slims_water_restriction_data import SlimsWaterRestrictionData

class TestSlimsWaterRestrictionData(unittest.TestCase):
    """SlimsWaterRestrictionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlimsWaterRestrictionData:
        """Test SlimsWaterRestrictionData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlimsWaterRestrictionData`
        """
        model = SlimsWaterRestrictionData()
        if include_optional:
            return SlimsWaterRestrictionData(
                content_event_created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                subject_id = '',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                assigned_by = '',
                target_weight_fraction = '',
                baseline_weight = '',
                weight_unit = ''
            )
        else:
            return SlimsWaterRestrictionData(
        )
        """

    def testSlimsWaterRestrictionData(self):
        """Test SlimsWaterRestrictionData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
