"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any

"""
This type stub file was generated by pyright.
"""
@dataclass
class Vote:
    """投票の内容を示す情報の構造体.

    Attributes:
        day (int): 投票が行われた日数.
        agent (str): 投票を行ったエージェントの名前.
        target (str): 投票の対象となったエージェントの名前.
    """
    day: int
    agent: str
    target: str
    @staticmethod
    def from_dict(obj: Any) -> Vote:
        ...
    


